---
title: "linear_models"
author: "Jasmine Zhang"
date: "2023-11-9"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
set.seed(1)
```

Load and clean the airbnb data

```{r}
data("nyc_airbnb")

nyc_airbnb = nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

## Fit a model
```{r}
fit = nyc_airbnb |> 
  lm(price ~ stars + borough, data = _)
#Look at the fit
summary(fit)
coef(fit)
```

Tidy up the output
```{r}
fit |> 
  broom::glance()
```
Tidy up the coefficients
```{r}
fit |> 
  broom::tidy() |> 
  mutate(term = str_replace(term, "^borough", "Borough: ")) |> 
  select(term, estimate, p.value) |> 
  knitr::kable(digits = 3)
```

## Fit another model
```{r}
fit = nyc_airbnb |> 
  mutate(borough = fct_infreq(borough),
         room_type = fct_infreq(room_type)) |> 
  lm(price ~ stars + borough + room_type, data = _)
fit |> 
  broom::tidy()
```

## Diagnostics

```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |>  #what happens when fit the model and apply on the dataset and calculate resid
  ggplot(aes(x = resid)) + geom_density() + xlim(-100, 500)

nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = borough, y = resid)) + geom_violin() 

nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) + geom_point() 
```

## Hypothesis testing: categorical predictor
fit a null and alternative model

```{r}
fit_null = lm(price ~ stars+borough, data = nyc_airbnb)
fit_alternative = lm(price ~ stars+borough+room_type, data = nyc_airbnb)

anova(fit_null, fit_alternative) |> 
  broom::tidy()
```

## Borough-level differences

```{r}
fit = nyc_airbnb |> 
  lm(price~stars*borough + room_type*borough, data = _) 
fit |> 
  broom::tidy()
```
fit seperate models and compare between boroughs

```{r}
airbnb_lm = function(df){
  lm(price~stars+room_type, data = df)
}
nyc_airbnb |> 
  nest(df = -borough) |> 
  mutate(models = map(df, airbnb_lm),
         results = map(models, broom::tidy)) |> 
           select(borough, results) |> 
           unnest(results) |> 
  select(borough, term, estimate) |> 
  pivot_wider(names_from =  term, values_from = estimate)
           
```

## Homicides in Baltimore 

```{r}
baltimore_df = 
  read_csv("data/homicide-data.csv") |> 
  filter(city == "Baltimore") |> 
  mutate(
    resolved = as.numeric(disposition == "Closed by arrest"),
    victim_age = as.numeric(victim_age),
    victim_race = fct_relevel(victim_race, "White")) |> 
  select(resolved, victim_age, victim_race, victim_sex)
```
fitting a logistic regression
```{r}
fit_logistic = baltimore_df |> 
  glm(resolved ~ victim_age + victim_race + victim_sex, data = _, family = binomial())

fit_logistic |> broom::tidy()
```

